/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#7cd9a1",
        "secondary-fixed": "#d6e3fb",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-secondary-fixed-variant": "#3b485a",
        "error": "#ba1a1a",
        "on-surface": "#131c28",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001f25",
        "inverse-surface": "#28313d",
        "on-secondary-fixed": "#0f1c2d",
        "on-surface-variant": "#3f484b",
        "secondary-container": "#d6e3fb",
        "on-secondary": "#ffffff",
        "primary": "#004550",
        "tertiary-container": "#00633a",
        "on-primary-container": "#93d5e4",
        "surface-dim": "#d1daeb",
        "secondary": "#525f73",
        "on-primary-fixed-variant": "#004e5a",
        "tertiary-fixed": "#98f6bb",
        "on-tertiary-container": "#81dea5",
        "on-background": "#131c28",
        "surface-variant": "#dae3f4",
        "outline": "#6f797b",
        "outline-variant": "#bfc8cb",
        "surface-container-high": "#e0e9f9",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dae3f4",
        "on-tertiary-fixed-variant": "#00522f",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#8fd1e0",
        "surface-bright": "#f8f9ff",
        "tertiary": "#004929",
        "on-tertiary-fixed": "#002110",
        "secondary-fixed-dim": "#bac7de",
        "on-error": "#ffffff",
        "primary-container": "#0f5e6b",
        "background": "#f8f9ff",
        "primary-fixed": "#abedfc",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#1e6774",
        "inverse-primary": "#8fd1e0",
        "on-secondary-container": "#586579"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "mono-data-sm": ["IBM Plex Mono", "monospace"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "mono-data-lg": ["IBM Plex Mono", "monospace"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "mono-data-md": ["IBM Plex Mono", "monospace"]
      },
      fontSize: {
        "headline-lg-mobile": ["1.25rem", { "lineHeight": "1.75rem", "fontWeight": "600" }],
        "headline-md": ["1.25rem", { "lineHeight": "1.75rem", "fontWeight": "600" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "fontWeight": "400" }],
        "body-md": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "headline-sm": ["1.125rem", { "lineHeight": "1.5rem", "fontWeight": "600" }],
        "mono-data-sm": ["0.75rem", { "lineHeight": "1rem", "fontWeight": "400" }],
        "label-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "headline-xl-mobile": ["1.5rem", { "lineHeight": "2rem", "fontWeight": "700" }],
        "mono-data-lg": ["1.125rem", { "lineHeight": "1.5rem", "fontWeight": "500" }],
        "headline-xl": ["2rem", { "lineHeight": "2.5rem", "fontWeight": "700" }],
        "headline-lg": ["1.5rem", { "lineHeight": "2rem", "fontWeight": "600" }],
        "label-md": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }],
        "mono-data-md": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }]
      }
    }
  }
}
