// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuditActivity
 */
export type AuditActivity = {
    /**
     * Id
     */
    id: number;
    /**
     * Action
     */
    action: string;
    /**
     * Entity
     */
    entity: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User Name
     */
    user_name: string | null;
};

/**
 * Body_create_study_studies_post
 */
export type BodyCreateStudyStudiesPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Body Part
     */
    body_part?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * History Flags
     */
    history_flags?: string | null;
};

/**
 * DailyCount
 */
export type DailyCount = {
    /**
     * Date
     */
    date: string;
    /**
     * Count
     */
    count: number;
};

/**
 * FindingFrequency
 */
export type FindingFrequency = {
    /**
     * Finding
     */
    finding: string;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: string;
    /**
     * Db
     */
    db: string;
};

/**
 * LatencyStatsResponse
 */
export type LatencyStatsResponse = {
    /**
     * Average Ms
     */
    average_ms: number;
    /**
     * P95 Ms
     */
    p95_ms: number;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ModelsStatusResponse
 */
export type ModelsStatusResponse = {
    /**
     * Models
     */
    models: Array<BackendAppApiHealthModelStatus>;
};

/**
 * QueueSizeResponse
 */
export type QueueSizeResponse = {
    /**
     * Awaiting Sign Off
     */
    awaiting_sign_off: number;
};

/**
 * ReviewRequest
 */
export type ReviewRequest = {
    /**
     * Decision
     */
    decision: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * StatusCounts
 */
export type StatusCounts = {
    /**
     * Uploaded
     */
    uploaded: number;
    /**
     * Processing
     */
    processing: number;
    /**
     * Done
     */
    done: number;
    /**
     * Rejected
     */
    rejected: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * StudyCountsResponse
 */
export type StudyCountsResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Today
     */
    today: number;
    by_status: StatusCounts;
    /**
     * Daily
     */
    daily: Array<DailyCount>;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Role
     */
    role: string;
    /**
     * Full Name
     */
    full_name: string;
};

/**
 * TriageDistributionResponse
 */
export type TriageDistributionResponse = {
    /**
     * High
     */
    high: number;
    /**
     * Medium
     */
    medium: number;
    /**
     * Low
     */
    low: number;
    /**
     * Needs Review
     */
    needs_review: number;
};

/**
 * UserClinic
 */
export type UserClinic = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Clinic Name
     */
    clinic_name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ModelStatus
 */
export type BackendAppApiDashboardModelStatus = {
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Status
     */
    status: string;
    /**
     * Metrics Link
     */
    metrics_link: string;
};

/**
 * ModelStatus
 */
export type BackendAppApiHealthModelStatus = {
    /**
     * Name
     */
    name: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Task
     */
    task: string;
    /**
     * Status
     */
    status: string;
    /**
     * Detail
     */
    detail?: string | null;
};

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ModelsStatusModelsStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models/status';
};

export type ModelsStatusModelsStatusGetResponses = {
    /**
     * Successful Response
     */
    200: ModelsStatusResponse;
};

export type ModelsStatusModelsStatusGetResponse = ModelsStatusModelsStatusGetResponses[keyof ModelsStatusModelsStatusGetResponses];

export type CreateStudyStudiesPostData = {
    body: BodyCreateStudyStudiesPost;
    path?: never;
    query?: never;
    url: '/studies';
};

export type CreateStudyStudiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStudyStudiesPostError = CreateStudyStudiesPostErrors[keyof CreateStudyStudiesPostErrors];

export type CreateStudyStudiesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StudyEventsStudiesIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/studies/{id}/events';
};

export type StudyEventsStudiesIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StudyEventsStudiesIdEventsGetError = StudyEventsStudiesIdEventsGetErrors[keyof StudyEventsStudiesIdEventsGetErrors];

export type StudyEventsStudiesIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudyResultStudiesIdResultGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/studies/{id}/result';
};

export type GetStudyResultStudiesIdResultGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudyResultStudiesIdResultGetError = GetStudyResultStudiesIdResultGetErrors[keyof GetStudyResultStudiesIdResultGetErrors];

export type GetStudyResultStudiesIdResultGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CompareStudiesStudiesIdCompareOtherIdPostData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
        /**
         * Other Id
         */
        other_id: number;
    };
    query?: never;
    url: '/studies/{id}/compare/{other_id}';
};

export type CompareStudiesStudiesIdCompareOtherIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareStudiesStudiesIdCompareOtherIdPostError = CompareStudiesStudiesIdCompareOtherIdPostErrors[keyof CompareStudiesStudiesIdCompareOtherIdPostErrors];

export type CompareStudiesStudiesIdCompareOtherIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudyImageStudiesIdImagePngGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/studies/{id}/image.png';
};

export type GetStudyImageStudiesIdImagePngGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudyImageStudiesIdImagePngGetError = GetStudyImageStudiesIdImagePngGetErrors[keyof GetStudyImageStudiesIdImagePngGetErrors];

export type GetStudyImageStudiesIdImagePngGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHeatmapStudiesIdHeatmapLabelPngGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
        /**
         * Label
         */
        label: string;
    };
    query?: never;
    url: '/studies/{id}/heatmap_{label}.png';
};

export type GetHeatmapStudiesIdHeatmapLabelPngGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHeatmapStudiesIdHeatmapLabelPngGetError = GetHeatmapStudiesIdHeatmapLabelPngGetErrors[keyof GetHeatmapStudiesIdHeatmapLabelPngGetErrors];

export type GetHeatmapStudiesIdHeatmapLabelPngGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReviewStudyStudiesIdReviewPostData = {
    body: ReviewRequest;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/studies/{id}/review';
};

export type ReviewStudyStudiesIdReviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewStudyStudiesIdReviewPostError = ReviewStudyStudiesIdReviewPostErrors[keyof ReviewStudyStudiesIdReviewPostErrors];

export type ReviewStudyStudiesIdReviewPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSkeletonMapAnatomySkeletonMapGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/anatomy/skeleton-map';
};

export type GetSkeletonMapAnatomySkeletonMapGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudyCountsDashboardStudiesCountsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/studies/counts';
};

export type GetStudyCountsDashboardStudiesCountsGetResponses = {
    /**
     * Successful Response
     */
    200: StudyCountsResponse;
};

export type GetStudyCountsDashboardStudiesCountsGetResponse = GetStudyCountsDashboardStudiesCountsGetResponses[keyof GetStudyCountsDashboardStudiesCountsGetResponses];

export type GetTriageDistributionDashboardStudiesTriageGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/studies/triage';
};

export type GetTriageDistributionDashboardStudiesTriageGetResponses = {
    /**
     * Successful Response
     */
    200: TriageDistributionResponse;
};

export type GetTriageDistributionDashboardStudiesTriageGetResponse = GetTriageDistributionDashboardStudiesTriageGetResponses[keyof GetTriageDistributionDashboardStudiesTriageGetResponses];

export type GetQueueSizeDashboardStudiesQueueGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/studies/queue';
};

export type GetQueueSizeDashboardStudiesQueueGetResponses = {
    /**
     * Successful Response
     */
    200: QueueSizeResponse;
};

export type GetQueueSizeDashboardStudiesQueueGetResponse = GetQueueSizeDashboardStudiesQueueGetResponses[keyof GetQueueSizeDashboardStudiesQueueGetResponses];

export type GetFindingFrequencyDashboardStudiesFindingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/studies/findings';
};

export type GetFindingFrequencyDashboardStudiesFindingsGetResponses = {
    /**
     * Response Get Finding Frequency Dashboard Studies Findings Get
     *
     * Successful Response
     */
    200: Array<FindingFrequency>;
};

export type GetFindingFrequencyDashboardStudiesFindingsGetResponse = GetFindingFrequencyDashboardStudiesFindingsGetResponses[keyof GetFindingFrequencyDashboardStudiesFindingsGetResponses];

export type GetRecentActivityDashboardAuditActivityGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/audit/activity';
};

export type GetRecentActivityDashboardAuditActivityGetResponses = {
    /**
     * Response Get Recent Activity Dashboard Audit Activity Get
     *
     * Successful Response
     */
    200: Array<AuditActivity>;
};

export type GetRecentActivityDashboardAuditActivityGetResponse = GetRecentActivityDashboardAuditActivityGetResponses[keyof GetRecentActivityDashboardAuditActivityGetResponses];

export type GetUsersClinicsDashboardUsersClinicsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/users/clinics';
};

export type GetUsersClinicsDashboardUsersClinicsGetResponses = {
    /**
     * Response Get Users Clinics Dashboard Users Clinics Get
     *
     * Successful Response
     */
    200: Array<UserClinic>;
};

export type GetUsersClinicsDashboardUsersClinicsGetResponse = GetUsersClinicsDashboardUsersClinicsGetResponses[keyof GetUsersClinicsDashboardUsersClinicsGetResponses];

export type GetModelStatusDashboardModelsStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/models/status';
};

export type GetModelStatusDashboardModelsStatusGetResponses = {
    /**
     * Response Get Model Status Dashboard Models Status Get
     *
     * Successful Response
     */
    200: Array<BackendAppApiDashboardModelStatus>;
};

export type GetModelStatusDashboardModelsStatusGetResponse = GetModelStatusDashboardModelsStatusGetResponses[keyof GetModelStatusDashboardModelsStatusGetResponses];

export type GetLatencyStatsDashboardStudiesLatencyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/studies/latency';
};

export type GetLatencyStatsDashboardStudiesLatencyGetResponses = {
    /**
     * Successful Response
     */
    200: LatencyStatsResponse;
};

export type GetLatencyStatsDashboardStudiesLatencyGetResponse = GetLatencyStatsDashboardStudiesLatencyGetResponses[keyof GetLatencyStatsDashboardStudiesLatencyGetResponses];
